import { HeaderType } from '../enums/mode';
import { Status } from '../enums/status';

export type Template = {
  id: number;
  name: string;
  category?: string;
  language?: string;
  status?: Status;
  messageSent?: number;
  messageOpen?: number;
  topBlockReason?: string;
  lastEdited?: string;
  headerType?: HeaderType | string;
  header?: any;
  body?: string;
  footer?: string;
};

export const templates: Template[] = [
  {
    id: 1,
    name: 'Template 1',
    category: 'Marketing',
    language: 'English',
    status: Status.ACTIVE,
    messageSent: 4,
    messageOpen: 2,
    topBlockReason: '',
    lastEdited: '2024-09-29',
  },
  {
    id: 2,
    name: 'Template 2',
    category: 'Sales',
    language: 'English',
    status: Status.REJECTED,
    messageSent: 10,
    messageOpen: 4,
    topBlockReason: 'Low engagement',
    lastEdited: '2024-09-28',
  },
  {
    id: 3,
    name: 'Template 3',
    category: 'Support',
    language: 'Spanish',
    status: Status.ACTIVE,
    messageSent: 15,
    messageOpen: 8,
    topBlockReason: '',
    lastEdited: '2024-09-30',
  },
  {
    id: 4,
    name: 'Template 4',
    category: 'Marketing',
    language: 'French',
    status: Status.ACTIVE,
    messageSent: 5,
    messageOpen: 2,
    topBlockReason: '',
    lastEdited: '2024-09-27',
  },
  {
    id: 5,
    name: 'Template 5',
    category: 'Sales',
    language: 'German',
    status: Status.REJECTED,
    messageSent: 8,
    messageOpen: 3,
    topBlockReason: 'Content issues',
    lastEdited: '2024-09-26',
  },
  {
    id: 6,
    name: 'Template 6',
    category: 'Support',
    language: 'English',
    status: Status.ACTIVE,
    messageSent: 12,
    messageOpen: 9,
    topBlockReason: '',
    lastEdited: '2024-09-25',
  },
  {
    id: 7,
    name: 'Template 7',
    category: 'Marketing',
    language: 'Spanish',
    status: Status.REJECTED,
    messageSent: 6,
    messageOpen: 1,
    topBlockReason: 'Outdated content',
    lastEdited: '2024-09-24',
  },
  {
    id: 8,
    name: 'Template 8',
    category: 'Sales',
    language: 'French',
    status: Status.ACTIVE,
    messageSent: 20,
    messageOpen: 10,
    topBlockReason: '',
    lastEdited: '2024-09-23',
  },
  {
    id: 9,
    name: 'Template 9',
    category: 'Support',
    language: 'German',
    status: Status.REJECTED,
    messageSent: 9,
    messageOpen: 4,
    topBlockReason: 'Formatting error',
    lastEdited: '2024-09-22',
  },
  {
    id: 10,
    name: 'Template 10',
    category: 'Marketing',
    language: 'English',
    status: Status.ACTIVE,
    messageSent: 11,
    messageOpen: 7,
    topBlockReason: '',
    lastEdited: '2024-09-21',
  },
  {
    id: 11,
    name: 'Template 11',
    category: 'Sales',
    language: 'Spanish',
    status: Status.ACTIVE,
    messageSent: 14,
    messageOpen: 6,
    topBlockReason: '',
    lastEdited: '2024-09-20',
  },
  {
    id: 12,
    name: 'Template 12',
    category: 'Support',
    language: 'French',
    status: Status.REJECTED,
    messageSent: 7,
    messageOpen: 2,
    topBlockReason: 'Low response rate',
    lastEdited: '2024-09-19',
  },
  {
    id: 13,
    name: 'Template 13',
    category: 'Marketing',
    language: 'German',
    status: Status.ACTIVE,
    messageSent: 18,
    messageOpen: 12,
    topBlockReason: '',
    lastEdited: '2024-09-18',
  },
  {
    id: 14,
    name: 'Template 14',
    category: 'Sales',
    language: 'English',
    status: Status.REJECTED,
    messageSent: 3,
    messageOpen: 0,
    topBlockReason: 'Invalid recipient list',
    lastEdited: '2024-09-17',
  },
  {
    id: 15,
    name: 'Template 15',
    category: 'Support',
    language: 'Spanish',
    status: Status.ACTIVE,
    messageSent: 16,
    messageOpen: 8,
    topBlockReason: '',
    lastEdited: '2024-09-16',
  },
  {
    id: 16,
    name: 'Template 16',
    category: 'Marketing',
    language: 'French',
    status: Status.REJECTED,
    messageSent: 10,
    messageOpen: 3,
    topBlockReason: 'Duplicate content',
    lastEdited: '2024-09-15',
  },
  {
    id: 17,
    name: 'Template 17',
    category: 'Sales',
    language: 'German',
    status: Status.ACTIVE,
    messageSent: 22,
    messageOpen: 13,
    topBlockReason: '',
    lastEdited: '2024-09-14',
  },
  {
    id: 18,
    name: 'Template 18',
    category: 'Support',
    language: 'English',
    status: Status.REJECTED,
    messageSent: 8,
    messageOpen: 3,
    topBlockReason: 'Spammy content',
    lastEdited: '2024-09-13',
  },
  {
    id: 19,
    name: 'Template 19',
    category: 'Marketing',
    language: 'Spanish',
    status: Status.ACTIVE,
    messageSent: 21,
    messageOpen: 11,
    topBlockReason: '',
    lastEdited: '2024-09-12',
  },
  {
    id: 20,
    name: 'Template 20',
    category: 'Sales',
    language: 'French',
    status: Status.ACTIVE,
    messageSent: 17,
    messageOpen: 9,
    topBlockReason: '',
    lastEdited: '2024-09-11',
  },
  {
    id: 21,
    name: 'Template 21',
    category: 'Support',
    language: 'German',
    status: Status.REJECTED,
    messageSent: 5,
    messageOpen: 1,
    topBlockReason: 'Poor content',
    lastEdited: '2024-09-10',
  },
];
